version: '3.8'

services:
  minimage:
    image: ghcr.io/s0urcelab/minimage:latest
    container_name: minimage
    ports:
      - "9527:9527"
    environment:
      - UPLOAD_AUTH_TOKEN=admin123 # 修改为您想要的鉴权值
      - MAX_FILE_SIZE_MB=10        # 文件体积限制（默认10MB）
      - FILE_LIFETIME=0            # 默认文件过期秒数（接口未指定时生效）
      - CLEANUP_INTERVAL=600       # 清理检查间隔（默认600=10分钟）
      - PUID=0                     # 设置UID
      - PGID=0                     # 设置GID
      - UMASK=022                  # 设置UMASK
    volumes:
      - ./data:/app/data  # 持久化存储
    restart: unless-stopped
